# Generated by Django 5.0.4 on 2024-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malayalam', models.TextField()),
                ('english', models.TextField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('consensus', models.BooleanField()),
            ],
        ),
    ]
