# Generated by Django 5.0.4 on 2024-05-02 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0026_delete_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('malayalam', models.TextField()),
                ('english', models.TextField()),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('consensus', models.BooleanField()),
                ('again', models.BooleanField(default=True)),
            ],
        ),
    ]
